package com.example.universitymarket.globals;

import java.util.HashMap;
import java.util.ArrayList;
import android.app.Application;

/**
 * <b>
 * ANY MODIFICATIONS WILL BE OVERWRITTEN ON BUILD 
 * </b><p>
 * Autogenerated on: Mar 6, 2024, 10:07:25 PM
 * <div>
 * File based on 'user_skeleton_cached.json' located at <a href="file:///Users/prestonscott/Desktop/OOSE/University-Market/UniversityMarket/app/src/main/res/raw/">main/res/raw/</a>
*/
public class ActiveUser extends Application {
    public static HashMap<String, String> about = null;
    public static String id = null;
    public static HashMap<String, Object> interactions = null;
    public static String tenant_id = null;
    public static String date_created = null;
    public static String domain = null;
    public static String last_name = null;
    public static String middle_name = null;
    public static String first_name = null;
    public static String username = null;
    public static ArrayList<Object> watch_ids = null;
    public static ArrayList<Object> transact_ids = null;
    public static ArrayList<Object> post_ids = null;

    @Override
    public void onCreate() {
        super.onCreate();
    }

}