package com.example.universitymarket.objects;

import java.util.HashMap;
import java.util.ArrayList;
import com.example.universitymarket.utilities.Data;

/**
 * <b>
 * ANY MODIFICATIONS WILL BE OVERWRITTEN ON BUILD 
 * </b><p>
 * Autogenerated on: Mar 7, 2024, 1:48:30 PM
 * <div>
 * File based on 'post_skeleton.json' located at <a href="file:///Users/prestonscott/Desktop/OOSE/University-Market/UniversityMarket/app/src/main/res/raw/">main/res/raw/</a>
*/
public class Post extends HashMap<String, Object> {
    private ArrayList<HashMap> descriptors = null;
    private HashMap<String, Object> about = null;
    private String id = null;
    private String date_created = null;
    private ArrayList<Object> transact_ids = null;
    private String genre = null;
    private String author_email = null;
    private ArrayList<Object> image_urls = null;
    private String list_price = null;
    private String item_title = null;
    private String item_description = null;
    private HashMap<String, Object> descriptorsMap = new HashMap<>();

    public Post(HashMap<String, Object> rawdata) {
        super.put("descriptors", rawdata.get("descriptors"));
        super.put("about", rawdata.get("about"));
        super.put("id", rawdata.get("id"));
        descriptors = (ArrayList<HashMap>) super.get("descriptors");
        about = (HashMap<String, Object>) super.get("about");
        id = (String) super.get("id");
        date_created = (String) about.get("date_created");
        transact_ids = (ArrayList<Object>) about.get("transact_ids");
        genre = (String) about.get("genre");
        author_email = (String) about.get("author_email");
        image_urls = (ArrayList<Object>) about.get("image_urls");
        list_price = (String) about.get("list_price");
        item_title = (String) about.get("item_title");
        item_description = (String) about.get("item_description");

        for(Object o : descriptors) {
            Data.mergeHash(descriptorsMap, (HashMap<String, Object>) o);
        }
    }

    public ArrayList<HashMap> getDescriptors() { return descriptors; }

    public HashMap<String, Object> getAbout() { return about; }

    public String getId() { return id; }

    public String getDateCreated() { return date_created; }

    public ArrayList<Object> getTransactIds() { return transact_ids; }

    public String getGenre() { return genre; }

    public String getAuthorEmail() { return author_email; }

    public ArrayList<Object> getImageUrls() { return image_urls; }

    public String getListPrice() { return list_price; }

    public String getItemTitle() { return item_title; }

    public String getItemDescription() { return item_description; }

    public HashMap<String, Object> getDescriptorsMap() { return descriptorsMap; }

    public void setDescriptors(ArrayList<HashMap> descriptors) { super.put("descriptors", descriptors); }

    public void setAbout(HashMap<String, Object> about) { super.put("about", about); }

    public void setId(String id) { super.put("id", id); }

    public HashMap<String, Object> getSuper() { return this; }
}