package com.example.universitymarket.objects;

import androidx.annotation.Discouraged;
import java.util.HashMap;
import java.util.ArrayList;

/**
 * <b>
 * ANY MODIFICATIONS WILL BE OVERWRITTEN ON BUILD 
 * </b><p>
 * Autogenerated on: Mar 20, 2024, 11:19:29 AM
 * <div>
 * File based on 'sample.json' located at <a href="file:///Users/prestonscott/Desktop/OOSE/University-Market/UniversityMarket/app/src/main/res/raw/">main/res/raw/</a>
*/
public class Sample extends HashMap<String, Object> {
    private String id = null;

    @Discouraged(message = "Unless you are initializing with data directly from database, do not use this constructor")
    public Sample(HashMap<String, Object> rawdata) {
        ArrayList<String> rawKeys = new ArrayList<>(rawdata != null ? rawdata.keySet() : new ArrayList<>());
        super.put("id", rawKeys.contains("id") ? rawdata.get("id") : null);
        ArrayList<String> superKeys = new ArrayList<>(super.keySet());
        id = superKeys.contains("id") ? (String) super.get("id") : null;
        formatSuper();
    }

    public Sample(String id) {
        this.id = id;
        formatSuper();
    }

    public Sample() {
        formatSuper();
    }

    public String getId() { return id; }

    public void setId(String id) {
        this.id = id;
        formatSuper();
    }

    public HashMap<String, Object> getSuper() { return this; }

    private void formatSuper() {
        super.clear();
        super.put("id", id);
    }
}