package com.example.universitymarket.objects;

import androidx.annotation.Discouraged;
import java.util.HashMap;
import java.util.ArrayList;
import com.example.universitymarket.utilities.Data;

/**
 * <b>
 * ANY MODIFICATIONS WILL BE OVERWRITTEN ON BUILD 
 * </b><p>
 * Autogenerated on: Mar 20, 2024, 11:35:02 AM
 * <div>
 * File based on 'transaction_skeleton.json' located at <a href="file:///Users/prestonscott/Desktop/OOSE/University-Market/UniversityMarket/app/src/main/res/raw/">main/res/raw/</a>
*/
public class Transaction extends HashMap<String, Object> {
    private ArrayList<HashMap> payments = new ArrayList<>();
    private HashMap<String, String> about = new HashMap<>();
    private String id = null;
    private String buyer_email = null;
    private String closing_date = null;
    private String seller_email = null;
    private String post_id = null;
    private String total_amount = null;
    private String status = null;
    private HashMap<String, Object> paymentsMap = new HashMap<>();

    @Discouraged(message = "Unless you are initializing with data directly from database, do not use this constructor")
    public Transaction(HashMap<String, Object> rawdata) {
        ArrayList<String> rawKeys = new ArrayList<>(rawdata != null ? rawdata.keySet() : new ArrayList<>());
        super.put("payments", rawKeys.contains("payments") ? rawdata.get("payments") : null);
        super.put("about", rawKeys.contains("about") ? rawdata.get("about") : null);
        super.put("id", rawKeys.contains("id") ? rawdata.get("id") : null);
        ArrayList<String> superKeys = new ArrayList<>(super.keySet());
        payments = superKeys.contains("payments") ? (ArrayList<HashMap>) super.get("payments") : null;
        about = superKeys.contains("about") ? (HashMap<String, String>) super.get("about") : null;
        id = superKeys.contains("id") ? (String) super.get("id") : null;
        ArrayList<String> aboutKeys = new ArrayList<>(about != null ? about.keySet() : new ArrayList<>());
        buyer_email = aboutKeys.contains("buyer_email") ? (String) about.get("buyer_email") : null;
        closing_date = aboutKeys.contains("closing_date") ? (String) about.get("closing_date") : null;
        seller_email = aboutKeys.contains("seller_email") ? (String) about.get("seller_email") : null;
        post_id = aboutKeys.contains("post_id") ? (String) about.get("post_id") : null;
        total_amount = aboutKeys.contains("total_amount") ? (String) about.get("total_amount") : null;
        status = aboutKeys.contains("status") ? (String) about.get("status") : null;

        for(int i = 0; payments != null && i < payments.size(); i++) {
            Data.mergeHash(paymentsMap, (HashMap<String, Object>) payments.get(i));
        }
        formatSuper();
    }

    public Transaction(ArrayList<HashMap> payments, String buyer_email, String closing_date, String seller_email, String post_id, String total_amount, String status, String id) {
        setAbout(buyer_email, closing_date, seller_email, post_id, total_amount, status);
        this.payments = payments;
        this.id = id;
        formatSuper();
    }

    public Transaction() {
        formatSuper();
    }

    public ArrayList<HashMap> getPayments() { return payments; }

    public HashMap<String, String> getAbout() { return about; }

    public String getId() { return id; }

    public String getBuyerEmail() { return buyer_email; }

    public String getClosingDate() { return closing_date; }

    public String getSellerEmail() { return seller_email; }

    public String getPostId() { return post_id; }

    public String getTotalAmount() { return total_amount; }

    public String getStatus() { return status; }

    public HashMap<String, Object> getPaymentsMap() { return paymentsMap; }

    public void setPayments(ArrayList<HashMap> payments) {
        this.payments = payments;
        formatSuper();
    }

    public void setAbout(String buyer_email, String closing_date, String seller_email, String post_id, String total_amount, String status) {
        this.buyer_email = buyer_email;
        this.closing_date = closing_date;
        this.seller_email = seller_email;
        this.post_id = post_id;
        this.total_amount = total_amount;
        this.status = status;
        formatSuper();
    }

    public void setId(String id) {
        this.id = id;
        formatSuper();
    }

    public void setBuyerEmail(String buyer_email) {
        this.buyer_email = buyer_email;
        formatSuper();
    }

    public void setClosingDate(String closing_date) {
        this.closing_date = closing_date;
        formatSuper();
    }

    public void setSellerEmail(String seller_email) {
        this.seller_email = seller_email;
        formatSuper();
    }

    public void setPostId(String post_id) {
        this.post_id = post_id;
        formatSuper();
    }

    public void setTotalAmount(String total_amount) {
        this.total_amount = total_amount;
        formatSuper();
    }

    public void setStatus(String status) {
        this.status = status;
        formatSuper();
    }

    public HashMap<String, Object> getSuper() { return this; }

    private void formatSuper() {
        about = new HashMap<>();
        about.put("buyer_email", buyer_email);
        about.put("closing_date", closing_date);
        about.put("seller_email", seller_email);
        about.put("post_id", post_id);
        about.put("total_amount", total_amount);
        about.put("status", status);
        super.clear();
        super.put("payments", payments);
        super.put("about", about);
        super.put("id", id);
    }
}