package com.example.universitymarket.objects;

import com.example.universitymarket.utilities.Data;
import java.util.HashMap;
import java.util.ArrayList;

/**
 * <b>
 * ANY MODIFICATIONS WILL BE OVERWRITTEN ON BUILD 
 * </b><p>
 * Autogenerated on: Mar 6, 2024, 9:54:43 PM
 * <div>
 * File based on 'user_skeleton.json' located at <a href="file:///Users/prestonscott/Desktop/OOSE/University-Market/UniversityMarket/app/src/main/res/raw/">main/res/raw/</a>
*/
public class User extends HashMap<String, Object> {
    private HashMap<String, String> about = null;
    private String id = null;
    private HashMap<String, Object> interactions = null;
    private String tenant_id = null;
    private String date_created = null;
    private String domain = null;
    private String last_name = null;
    private String middle_name = null;
    private String first_name = null;
    private String username = null;
    private ArrayList<Object> watch_ids = null;
    private ArrayList<Object> transact_ids = null;
    private ArrayList<Object> post_ids = null;

    public User(HashMap<String, Object> rawdata) {
        super.put("about", rawdata.get("about"));
        super.put("id", rawdata.get("id"));
        super.put("interactions", rawdata.get("interactions"));
        about = (HashMap<String, String>) super.get("about");
        id = (String) super.get("id");
        interactions = (HashMap<String, Object>) super.get("interactions");
        tenant_id = (String) about.get("tenant_id");
        date_created = (String) about.get("date_created");
        domain = (String) about.get("domain");
        last_name = (String) about.get("last_name");
        middle_name = (String) about.get("middle_name");
        first_name = (String) about.get("first_name");
        username = (String) about.get("username");
        watch_ids = (ArrayList<Object>) interactions.get("watch_ids");
        transact_ids = (ArrayList<Object>) interactions.get("transact_ids");
        post_ids = (ArrayList<Object>) interactions.get("post_ids");
    }

    public HashMap<String, String> getAbout() { return about; }

    public String getId() { return id; }

    public HashMap<String, Object> getInteractions() { return interactions; }

    public String getTenantId() { return tenant_id; }

    public String getDateCreated() { return date_created; }

    public String getDomain() { return domain; }

    public String getLastName() { return last_name; }

    public String getMiddleName() { return middle_name; }

    public String getFirstName() { return first_name; }

    public String getUsername() { return username; }

    public ArrayList<Object> getWatchIds() { return watch_ids; }

    public ArrayList<Object> getTransactIds() { return transact_ids; }

    public ArrayList<Object> getPostIds() { return post_ids; }

    public void setAbout(HashMap<String, String> about) { super.put("about", about); }

    public void setId(String id) { super.put("id", id); }

    public void setInteractions(HashMap<String, Object> interactions) { super.put("interactions", interactions); }

    public HashMap<String, Object> getSuper() { return this; }
}