package com.example.universitymarket.objects;

import androidx.annotation.Discouraged;
import java.util.HashMap;
import java.util.ArrayList;

/**
 * <b>
 * ANY MODIFICATIONS WILL BE OVERWRITTEN ON BUILD 
 * </b><p>
 * Autogenerated on: Mar 20, 2024, 11:35:02 AM
 * <div>
 * File based on 'user_skeleton_cached.json' located at <a href="file:///Users/prestonscott/Desktop/OOSE/University-Market/UniversityMarket/app/src/main/res/raw/">main/res/raw/</a>
*/
public class User extends HashMap<String, Object> {
    private HashMap<String, String> about = new HashMap<>();
    private String id = null;
    private HashMap<String, ArrayList> interactions = new HashMap<>();
    private String date_created = null;
    private String last_name = null;
    private String middle_name = null;
    private String first_name = null;
    private String email = null;
    private String username = null;
    private ArrayList<String> watch_ids = new ArrayList<>();
    private ArrayList<String> transact_ids = new ArrayList<>();
    private ArrayList<String> post_ids = new ArrayList<>();

    @Discouraged(message = "Unless you are initializing with data directly from database, do not use this constructor")
    public User(HashMap<String, Object> rawdata) {
        ArrayList<String> rawKeys = new ArrayList<>(rawdata != null ? rawdata.keySet() : new ArrayList<>());
        super.put("about", rawKeys.contains("about") ? rawdata.get("about") : null);
        super.put("id", rawKeys.contains("id") ? rawdata.get("id") : null);
        super.put("interactions", rawKeys.contains("interactions") ? rawdata.get("interactions") : null);
        ArrayList<String> superKeys = new ArrayList<>(super.keySet());
        about = superKeys.contains("about") ? (HashMap<String, String>) super.get("about") : null;
        id = superKeys.contains("id") ? (String) super.get("id") : null;
        interactions = superKeys.contains("interactions") ? (HashMap<String, ArrayList>) super.get("interactions") : null;
        ArrayList<String> aboutKeys = new ArrayList<>(about != null ? about.keySet() : new ArrayList<>());
        date_created = aboutKeys.contains("date_created") ? (String) about.get("date_created") : null;
        last_name = aboutKeys.contains("last_name") ? (String) about.get("last_name") : null;
        middle_name = aboutKeys.contains("middle_name") ? (String) about.get("middle_name") : null;
        first_name = aboutKeys.contains("first_name") ? (String) about.get("first_name") : null;
        email = aboutKeys.contains("email") ? (String) about.get("email") : null;
        username = aboutKeys.contains("username") ? (String) about.get("username") : null;
        ArrayList<String> interactionsKeys = new ArrayList<>(interactions != null ? interactions.keySet() : new ArrayList<>());
        watch_ids = interactionsKeys.contains("watch_ids") ? (ArrayList<String>) interactions.get("watch_ids") : null;
        transact_ids = interactionsKeys.contains("transact_ids") ? (ArrayList<String>) interactions.get("transact_ids") : null;
        post_ids = interactionsKeys.contains("post_ids") ? (ArrayList<String>) interactions.get("post_ids") : null;
        formatSuper();
    }

    public User(String date_created, String last_name, String middle_name, String first_name, String email, String username, String id, ArrayList<String> watch_ids, ArrayList<String> transact_ids, ArrayList<String> post_ids) {
        setAbout(date_created, last_name, middle_name, first_name, email, username);
        setInteractions(watch_ids, transact_ids, post_ids);
        this.id = id;
        formatSuper();
    }

    public User(String id) {
        this.id = id;
        formatSuper();
    }

    public HashMap<String, String> getAbout() { return about; }

    public String getId() { return id; }

    public HashMap<String, ArrayList> getInteractions() { return interactions; }

    public String getDateCreated() { return date_created; }

    public String getLastName() { return last_name; }

    public String getMiddleName() { return middle_name; }

    public String getFirstName() { return first_name; }

    public String getEmail() { return email; }

    public String getUsername() { return username; }

    public ArrayList<String> getWatchIds() { return watch_ids; }

    public ArrayList<String> getTransactIds() { return transact_ids; }

    public ArrayList<String> getPostIds() { return post_ids; }

    public void setAbout(String date_created, String last_name, String middle_name, String first_name, String email, String username) {
        this.date_created = date_created;
        this.last_name = last_name;
        this.middle_name = middle_name;
        this.first_name = first_name;
        this.email = email;
        this.username = username;
        formatSuper();
    }

    public void setId(String id) {
        this.id = id;
        formatSuper();
    }

    public void setInteractions(ArrayList<String> watch_ids, ArrayList<String> transact_ids, ArrayList<String> post_ids) {
        this.watch_ids = watch_ids;
        this.transact_ids = transact_ids;
        this.post_ids = post_ids;
        formatSuper();
    }

    public void setDateCreated(String date_created) {
        this.date_created = date_created;
        formatSuper();
    }

    public void setLastName(String last_name) {
        this.last_name = last_name;
        formatSuper();
    }

    public void setMiddleName(String middle_name) {
        this.middle_name = middle_name;
        formatSuper();
    }

    public void setFirstName(String first_name) {
        this.first_name = first_name;
        formatSuper();
    }

    public void setEmail(String email) {
        this.email = email;
        formatSuper();
    }

    public void setUsername(String username) {
        this.username = username;
        formatSuper();
    }

    public void setWatchIds(ArrayList<String> watch_ids) {
        this.watch_ids = watch_ids;
        formatSuper();
    }

    public void setTransactIds(ArrayList<String> transact_ids) {
        this.transact_ids = transact_ids;
        formatSuper();
    }

    public void setPostIds(ArrayList<String> post_ids) {
        this.post_ids = post_ids;
        formatSuper();
    }

    public HashMap<String, Object> getSuper() { return this; }

    private void formatSuper() {
        interactions = new HashMap<>();
        interactions.put("watch_ids", watch_ids);
        interactions.put("transact_ids", transact_ids);
        interactions.put("post_ids", post_ids);
        about = new HashMap<>();
        about.put("date_created", date_created);
        about.put("last_name", last_name);
        about.put("middle_name", middle_name);
        about.put("first_name", first_name);
        about.put("email", email);
        about.put("username", username);
        super.clear();
        super.put("about", about);
        super.put("id", id);
        super.put("interactions", interactions);
    }
}