package com.example.universitymarket.globals.actives;

import androidx.annotation.Discouraged;
import java.util.HashMap;
import java.util.ArrayList;
import android.app.Application;

/**
 * <b>
 * ANY MODIFICATIONS WILL BE OVERWRITTEN ON BUILD 
 * </b><p>
 * Autogenerated on: Mar 20, 2024, 11:35:02 AM
 * <div>
 * File based on 'user_skeleton_cached.json' located at <a href="file:///Users/prestonscott/Desktop/OOSE/University-Market/UniversityMarket/app/src/main/res/raw/">main/res/raw/</a>
*/
public class ActiveUser extends Application {
    public static HashMap<String, String> about = new HashMap<>();
    public static String id = null;
    public static HashMap<String, ArrayList> interactions = new HashMap<>();
    public static String date_created = null;
    public static String last_name = null;
    public static String middle_name = null;
    public static String first_name = null;
    public static String email = null;
    public static String username = null;
    public static ArrayList<String> watch_ids = new ArrayList<>();
    public static ArrayList<String> transact_ids = new ArrayList<>();
    public static ArrayList<String> post_ids = new ArrayList<>();

}