package com.example.universitymarket.globals.actives;

import androidx.annotation.Discouraged;
import java.util.HashMap;
import java.util.ArrayList;
import com.example.universitymarket.utilities.Data;
import android.app.Application;

/**
 * <b>
 * ANY MODIFICATIONS WILL BE OVERWRITTEN ON BUILD 
 * </b><p>
 * Autogenerated on: Mar 20, 2024, 11:19:29 AM
 * <div>
 * File based on 'transaction_skeleton_cached.json' located at <a href="file:///Users/prestonscott/Desktop/OOSE/University-Market/UniversityMarket/app/src/main/res/raw/">main/res/raw/</a>
*/
public class ActiveTransaction extends Application {
    public static ArrayList<HashMap> payments = new ArrayList<>();
    public static HashMap<String, String> about = new HashMap<>();
    public static String id = null;
    public static String buyer_email = null;
    public static String closing_date = null;
    public static String seller_email = null;
    public static String post_id = null;
    public static String total_amount = null;
    public static String status = null;
    public static HashMap<String, Object> paymentsMap = new HashMap<>();

}